server:
  port: 8009
springdoc:
  swagger-ui:
    path: "/api-docs"
spring:
  rabbitmq:
    host: 10.110.0.89
    port: 5672
    username: guest
    password: guest
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/conta