server:
  port: 8009
springdoc:
  swagger-ui:
    path: "/api-docs"
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bancotads@gmail.com
    password: ytac ojih mkqx uztb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: orquestrador
  rabbitmq:
    host: host.docker.internal
#    host: 10.110.0.95
    port: 5672
    username: guest
    password: guest