server:
  port: 8009
springdoc:
  swagger-ui:
    path: "/api-docs"
spring:
  application:
    name: orquestrador
  rabbitmq:
    host: host.docker.internal
#    host: 10.110.0.95
    port: 5672
    username: guest
    password: guest