server:
  port: 8008
springdoc:
  swagger-ui:
    path: "/api-docs"
spring:
  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://root:@192.168.0.183:3306/cliente